# Generated by Django 3.1 on 2020-09-22 00:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombredia', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('especialidadId', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=70)),
            ],
            options={
                'db_table': 'gestionturnos_especialidad',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('medicoId', models.AutoField(primary_key=True, serialize=False)),
                ('matriculaId', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('dni', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ObraSocial',
            fields=[
                ('ObraSocialId', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('TurnoId', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_registro', models.DateField(default=django.utils.timezone.now)),
                ('fecha_turno', models.DateField()),
                ('dni', models.IntegerField()),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.PositiveSmallIntegerField(null=True)),
                ('telefono', models.CharField(max_length=13)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otros')], max_length=1)),
                ('mail', models.EmailField(max_length=50)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.especialidad')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.medico')),
                ('obrasocial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.obrasocial')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='medico',
            name='obrasocial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.obrasocial'),
        ),
        migrations.CreateModel(
            name='EspecialidadMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.especialidad')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.medico')),
            ],
        ),
    ]
