# Generated by Django 3.1 on 2020-09-22 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0004_auto_20200921_2129'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaMedico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombredia', models.CharField(max_length=70)),
                ('hora_desde', models.TimeField()),
                ('hora_hasta', models.TimeField()),
                ('duracion', models.IntegerField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turnos.medico')),
            ],
        ),
    ]
