# Generated by Django 3.1 on 2020-09-22 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0005_reservamedico'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dias',
        ),
    ]
