# Generated by Django 3.1 on 2020-09-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0006_delete_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='dias',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
