# Generated by Django 3.1 on 2020-09-22 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0007_turno_dias'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReservaMedico',
            new_name='ConfiguracionHoraria',
        ),
    ]
