# Generated by Django 3.1 on 2020-09-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0009_auto_20200922_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='horas',
        ),
        migrations.AddField(
            model_name='turno',
            name='hora_turno',
            field=models.TimeField(null=True),
        ),
    ]
